CREATE TABLE `promotion_promotion` (
`ID` INT(11) NOT NULL AUTO_INCREMENT,
`PROMOTION_ID` INT(11) NOT NULL UNIQUE,
`HB_ID` INT(11),
`SLIDER_ID` INT(11),
`PREVIEW_PICTURE` INT(11) ,
`DETAIL_PICTURE` INT(11) ,
`DETAIL_TEXT` text COLLATE utf8_unicode_ci,
`PREVIEW_TEXT` text COLLATE utf8_unicode_ci,
`STYLES` text COLLATE utf8_unicode_ci,
`ABANDONED_CARD` VARCHAR(255) DEFAULT 'N',
`DISCOUNT_REGISTR` VARCHAR(255) DEFAULT 'N',
`CLEAR_CACHE` VARCHAR(255) DEFAULT 'N',
 PRIMARY KEY (ID)
)ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
-- CREATE INDEX promotion
-- ON `promotion_promotion` (`PROMOTION_ID`);